apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ffmpeg-worker-hpa
  labels:
    app: media-encode-pipeline
    component: ffmpeg-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ffmpeg-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  - type: Pods
    pods:
      metric:
        name: rabbitmq_messages_ready
      target:
        type: AverageValue
        averageValue: 100

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qc-worker-hpa
  labels:
    app: media-encode-pipeline
    component: qc-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qc-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  - type: Pods
    pods:
      metric:
        name: rabbitmq_messages_ready
      target:
        type: AverageValue
        averageValue: 100
